select*from me.employees;
SELECT * FROM employees where HIRE_DATE like '2005%';
SELECT distinct JOB_ID FROM employees ORDER BY JOB_ID ASC;

SELECT FIRST_NAME, LAST_NAME FROM employees WHERE NOT COMMISSION_PCT IS NULL ;

SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE '_a%';

SELECT * FROM departments ORDER BY DEPARTMENT_NAME;
SELECT STREET_ADDRESS from locations WHERE COUNTRY_ID like 'IT';

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees WHERE LAST_NAME LIKE 'Mc%';
SELECT FIRST_NAME, LAST_NAME FROM employees WHERE FIRST_NAME LIKE '_H%' or LAST_NAME LIKE '_H%';

